spring.application.name=Railway_Train_Search_System

spring.datasource.url=jdbc:mysql://localhost:3306/railway_train_search_system
spring.datasource.username=root
spring.datasource.password=Root@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

